### ISSUE TITLE
Filter testcase

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [Subito-it/Mendoza#9]
Add support for filtering test cases via the plugin architecture, Using Slang can help make it easier to filter the swift code  https://github.com/Swifteroid/Slang/pull/2

**Comment by tcamin** [comment]
I really appreciate the effort with the open PRs however I truely believe that the right way to approach this is by improving the current plugin implementation. I'm really happy with the choice of the plugins from an architectural point of view because it allows to keep the code of Mendoza to a bare minimum. I'm equally unhappy with the current implementation which is definitely not user friendly. You can use Xcode to write the plugins but it involves a few manual steps which are everything but obvious.

I would like to see an improved version of the plugin init command which produces an Xcode project with targets for each plugin. Mendoza could build these targets and invoke the compiled executables. This would allow a much easier integration of external dependencies in plugins which now require you to use swift-sh. As soon as I'll be able to allocate some time I'll try to come out with something but I'm definitely open to suggestions/initial implementation.

UI testing parallization on multiple machines is such a niche that it's really not worth the effort of adding features that may not be enough for the unique needs of every user. The risk is that the complexity of the tool just increases indefinitely. Instead I would invest time in improving the plugin development experience which for example in our case proved to work really well. Our plugins do custom things like extracting execution time from previous runs (to improve test execution order), update of internal tools on completion and so on. Tests are decorated to run only on specific devices/size so extraction has again a completely custom plugin implementation. I figure this will probably be the case for other Mendoza users. Hope you understand my point.
